version: '3.8'

services:
  # Frontend client
  client:
    container_name: client 
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    env_file:
      - ./client/.env.dev
    depends_on:
      - api
    networks:
      - flowops-network-dev

  # API Service (Monolithic)
  api:
    container_name: flowops-api-dev
    build:
      context: ./FlowOps
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-3000}:${APP_PORT:-3000}"
    volumes:
      - ./FlowOps:/app
      - /app/node_modules
      - prisma_cache:/root/.cache/prisma
    env_file:
      - ./.env.dev
    environment:
      - APP_PORT=${APP_PORT:-3000}
      - APP_NAME=${APP_NAME:-flowops}-api
      - NODE_ENV=development
    depends_on:
      - mongodb
    networks:
      - flowops-network-dev

  # MongoDB Service
  mongodb:
    image: mongo:latest
    container_name: flowops-mongodb-dev
    volumes:
      - mongodb_data_dev:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=flowops
    networks:
      - flowops-network-dev

networks:
  flowops-network-dev:
    driver: bridge

volumes:
  mongodb_data_dev:
  prisma_cache: 