version: '3.8'

services:
  client:
    container_name: client  
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
      - NODE_ENV=development
    depends_on:
      - api-gateway
    command: npm run dev

  # api:
  #   container_name: api
  #   build:
  #     context: ./api
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./api:/app
  #   environment:
  #     - DEBUG=1
  #     - DJANGO_SECRET_KEY=your-secret-key-here
  #     - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
  #     - SQL_ENGINE=django.db.backends.postgresql
  #     - SQL_DATABASE=mydatabase
  #     - SQL_USER=myuser
  #     - SQL_PASSWORD=mypassword
  #     - SQL_HOST=db
  #     - SQL_PORT=5432
  #   depends_on:
  #     - db
  #   command: python manage.py runserver 0.0.0.0:8000

  api-gateway:
    container_name: api-gateway
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - FRONTEND_URL=http://localhost:5173
    depends_on:
      - db


  db:
    image: postgres:15
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5432:5432"

volumes:
  postgres_data: 