version: '3.8'

services:
  # Frontend client
  client:
    container_name: flowops-client
    build:
      context: ./client
      dockerfile: Dockerfile
      target: production
    ports:
      - "80:80"  # Production port
    env_file:
      - ./client/.env.prod
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - flowops-network

  # API 
  api:
    container_name: flowops-api
    build:
      context: ./FlowOps
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-3000}:${APP_PORT:-3000}"
    env_file:
      - ./.env.prod
    environment:
      - APP_PORT=${APP_PORT:-3000}
      - APP_NAME=flowops-api
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - mongodb
    networks:
      - flowops-network

  # MongoDB Service
  mongodb:
    image: mongo:latest
    container_name: flowops-mongodb
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=flowops
    restart: unless-stopped
    networks:
      - flowops-network

networks:
  flowops-network:
    driver: bridge

volumes:
  mongodb_data: