version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: flowops-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=flowops
    networks:
      - flowops-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: flowops-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - flowops-network

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flowops-api-gateway
    ports:
      - "3000:3000"
    environment:
      - APP_NAME=flowops-api
      - APP_VERSION=1.0.0
      - APP_HOST=0.0.0.0
      - APP_PORT=3000
      - DEBUG=true
      - MONGODB_URI=mongodb://mongodb:27017/flowops
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672
      - RABBITMQ_EXCHANGE=flowops
      - RABBITMQ_QUEUE=workflows
      - SERVICES_WORKFLOW_URL=http://workflow-service:3001
      - ALLOW_ORIGINS=*
      - ALLOW_CREDENTIALS=false
      - ALLOW_METHODS=GET,POST,PUT,DELETE
      - ALLOW_HEADERS=Content-Type,Authorization
    depends_on:
      - mongodb
      - rabbitmq
      - workflow-service
    networks:
      - flowops-network

  workflow-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flowops-workflow-service
    ports:
      - "3001:3001"
    environment:
      - APP_NAME=flowops-workflow-service
      - APP_VERSION=1.0.0
      - APP_HOST=0.0.0.0
      - APP_PORT=3001
      - DEBUG=true
      - MONGODB_URI=mongodb://mongodb:27017/flowops
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672
      - RABBITMQ_EXCHANGE=flowops
      - RABBITMQ_QUEUE=workflows
      - ALLOW_ORIGINS=*
      - ALLOW_CREDENTIALS=false
      - ALLOW_METHODS=GET,POST,PUT,DELETE
      - ALLOW_HEADERS=Content-Type,Authorization
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - flowops-network

networks:
  flowops-network:
    driver: bridge

volumes:
  mongodb_data:
  rabbitmq_data: 