version: "3.8"

services:
  gateway:
    build: ./gateway
    container_name: gateway
    volumes:
      - ./gateway:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - workflow_service

  workflow_service:
    build: ./workflow_service
    container_name: workflow_service
    volumes:
      - ./workflow_service:/app
    ports:
      - "8100:8100"
    depends_on:
      - rabbitmq
      - mongo
    environment:
      MONGO_CONNECTION_STRING: mongodb://root:example@mongo:27017/
      MONGO_DB_NAME: flowops
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASS: password

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongo_data: 